### ISSUE TITLE
Not able to get it working

### ISSUE THREAD

**Issue by emekaelo** [martingrosche/notion-2-issue#10]
## Describe the bug
The issues don't show up in the GitHub repo after it's been created and then manually triggering the action

##  To Reproduce
List of steps to reproduce the behavior.
I followed the steps in the action marketplace

## Expected behavior
I expected the issues created in Notion to appear on the GitHub repo

## Versions
- Action: 1.0.0
- Notion: 2.36

## Additional context
It's a private repo

Workflow below
```yml
name: Notion Database
on: workflow_dispatch
permissions:
  contents: read
  repository-projects: read
  issues: write
jobs:
  sync-github-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run Action
        uses: martingrosche/notion-2-issue@v1.0.0
        with:
          notionToken: ${{ secrets.NOTION_TOKEN }}
          notionDatabase: ${{ secrets.NOTION_DATABASE }}

```
